overviews/urls.py
from django.urls import path
from . import views

app_name = "overviews"

urlpatterns = [
    path('students_list/', views.StudentsListView.as_view(), name="students_list"),
    path('departments_list/', views.DepartmentsListView.as_view(), name="departments_list"),
    path('curriculum/<int:dep_id>', views.curriculum_view, name="curriculum"),
    path('students_list/<int:pk>/', views.StudentsDetailView.as_view()),

]

registrations/urls.py
from django.urls import path
from . import views

app_name = "registrations"

urlpatterns = [
    path('',views.RegistrationHomeView.as_view(), name="index"),
    path('faculties_form/',views.AddFacultyView.as_view(),name="faculties_form"),
    path('departments_form/',views.AddDepartmentView.as_view(), name="departments_form"),
    path('academicstaff_form/', views.AddAcademicStaffView.as_view(), name="academicstaff_form"),
    path('students_form/', views.AddStudentView.as_view(), name="students_form"),
    path('curriculums_form/', views.AddCurriculumView.as_view(), name="curriculums_form"),
    # path('curriculum/<int:depid>/',views.deneme, name="deneme"),




    
]

unis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_view),
    path('registrations/', include("registrations.urls")),
    path('overviews/', include("overviews.urls")),
    
]

overviews/models.py
from django.db import models

# Create your models here.

overviews/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.db.models import Sum

from registrations.models import Students, Departments, Curriculums, InstructionalPlan

# Create your views here.

class StudentsListView(ListView):
    model = Students
    context_object_name = "students_list"
    template_name = "overviews/students_list.html"

class DepartmentsListView(ListView):
    model = Departments
    context_object_name = "departments_list"
    template_name = "overviews/departments_list.html"

def curriculum_view(request, dep_id):
    curriculum_data = Curriculums.objects.filter(department_id = dep_id).order_by('term')
    curriculum_hours_sum = curriculum_data.aggregate(Sum('theortical_hours'))
    practical_hours_sum = curriculum_data.aggregate(Sum('practical_hours'))
    ects_sum = curriculum_data.aggregate(Sum('ects'))
    var = {
        "curriculum_data":curriculum_data, "curriculum_hours_sum":curriculum_hours_sum,
        "practical_hours_sum":practical_hours_sum,
        "ects_sum":ects_sum
        }
    return render(request,"overviews/curriculum.html",context=var)


class StudentsDetailView(DetailView):
    model = Students



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        inst_plan = InstructionalPlan.objects.filter(student_id = self.kwargs.get('pk')).order_by('curriculum__term')
        context["inst_plan"] = inst_plan
        return context
    

unis/views.py
from django.shortcuts import render
from registrations.models import Students

def home_view(request):
    active_student_number = len(Students.objects.filter(status="Active"))

    data = {"active_students":active_student_number}
    return render(request,"home.html", context=data)

overviews/templates/overviews/curriculum.html
{% extends 'base.html' %}


{% block body %}

<div class="container">

    <br>
    <h4>CURRICULUM OF THE {{data.department}} DEPARTMENT</h4>
    <br>

    <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">TERM</th>
            <th scope="col">TYPE</th>
            <th scope="col">CODE</th>
            <th scope="col">TITLE</th>
            <th scope="col">TH</th>
            <th scope="col">PH</th>
            <th scope="col">ECTS</th>
          </tr>
        </thead>
        <tbody>
            {% for cur in curriculum_data %}
            <tr>
                <th scope="row">{{cur.term}}</th>
                <td>{{cur.course_type}}</td>
                <td>{{cur.code}} </td>
                <td>{{cur.title}}</td>
                <td>{{cur.theortical_hours}}</td>
                <td>{{cur.practical_hours}}</td>
                <td>{{cur.ects}}</td>
              </tr>
            {% endfor %}
            <tr>
                <th scope="row"></th>
                <td></td>
                <td></td>
                <td><b>TOTAL</b></td>
                <td><b>{{curriculum_hours_sum.theortical_hours__sum}}</b></td>
                <td><b>{{practical_hours_sum.practical_hours__sum}}</b></td>
                <td><b>{{ects_sum.ects__sum}}</b></td>


              </tr>
          
        </tbody>
      </table>

      <br>
      <br>
      <br>
      <i>* C: Compulsory <br>* TH: Theorotical Hours <br>* PH: Practical Hours </i>
</div>

{% endblock body %}

overviews/templates/overviews/departments_list.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
<br>
    <h4 style="text-align:center;">ALL DEPARTMENTS</h4>
<br>

    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Faculty</th>
            <th scope="col">Department</th>
            <th scope="col">Department Code</th>
          </tr>
        </thead>
        <tbody>
            {% for dep in departments_list %}
            <tr>
                <th scope="row">{{dep.faculty}}</th>
                <td> <a href="/overviews/curriculum/{{dep.id}}">{{dep.department}}</a>
                    </td>
                <td>{{dep.department_code}}</td>
              </tr>
            {% endfor %}

          
        </tbody>
      </table>

</div>

{% endblock body %}

overviews/templates/overviews/students_list.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
<h4 style="text-align:center;">ALL STUDENTS</h4>

    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">School ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Faculty</th>
            <th scope="col">Department</th>
            <th scope="col">Advisor</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
            {% for student in students_list %}
            <tr>
                <th scope="row"><a href="{{student.pk}}">{{student.school_id}}</a></th>
                <td>{{student.first_name}}</td>
                <td>{{student.last_name}}</td>
                <td>{{student.faculty}}</td>
                <td>{{student.department}}</td>
                <td>{{student.advisor}}</td>
                {% if student.status == "Active" %}
                <td><b style="color:green;">{{student.status}}</b></td>
                {% else %}
                <td>{{student.status}}</td>
                {% endif %}
              </tr>
            {% endfor %}

          
        </tbody>
      </table>






</div>

{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <title>UN - INFORMATION SYSTEM</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'registrations:index' %}" role="button" data-bs-toggle="dropdown" aria-expand="false">Registrations</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'registrations:faculties_form' %}">Add a New Faculty</a></li>
                    <li><a class="dropdown-item" href="{% url 'registrations:departments_form' %}">Add a New Department</a></li>
                    <li><a class="dropdown-item" href="{% url 'registrations:academicstaff_form' %}">Add a New Academic Staff</a></li>
                    <li><a class="dropdown-item" href="{% url 'registrations:students_form' %}">Add a New Student</a></li>
                    <li><a class="dropdown-item" href="{% url 'registrations:curriculums_form' %}">Add to Curriculum</a></li>
                  </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expand="false">Overviews</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'overviews:students_list' %}">Students List</a></li>
                    <li><a class="dropdown-item" href="{% url 'overviews:departments_list' %}">Departments List</a></li>
                  </ul>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expand="false">Academic Units</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="">Add a New Faculty</a></li>
                    <li><a class="dropdown-item" href="">Add a New Program</a></li>
                    <li><a class="dropdown-item" href="">Add to Curriculum</a></li>
                  </ul>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown link
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% if messages %}
      {% for message in messages %}
          <div class="text-center alert alert-{{ message.tags }}">
              {{ message|safe }}
          </div>
      {% endfor %}
     {% endif %}

    {% block body %}


    {% endblock body %}


</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block body %}


<div class="container">
    <h4>
        WELCOME TO UNIVERSITY OF NOWHERE <br>
        INFORMATION SYSTEM
    </h4>
    <br>
    <hr>
    <br>
    <b>Our Total Active Student Number: {{active_students}}</b> 

</div>



{% endblock body %}